#List of characters from which the password can be made
a=['A':'Z';'a':'z';'0':'9';'~';'!';'@';'#';'$';'%';'^';'&';'*';'(';')';'_';'+';'=';'-';'`']
using Random
using Distributions
Random.seed!(1)
password=rand(a,8)
store_count=0 #variable to store to count if 2 or more match
for _ in 1:1000000
    hacker_gen=rand(a,8) #password generated by hacker
    if sum(password.==hacker_gen)>=2 #if more than 2 matches increment count
        global store_count+=1
    end
end
store_count/=1000000
println("The probability of a password getting stored in the database is ",store_count)
#theoretical answer is a binomial distribution with p=1/78
binom=Binomial(8, 1/78)
#1-P(X=0)-P(X=1)
theoretical=1-pdf(binom,0)-pdf(binom,1)
println("The theoretical answer is ",theoretical)
println("The difference is ",theoretical-store_count)